default_stages: [push]
repos:
-   repo: local
    hooks:
    -   id: run-smk-test
        name: run smoke test
        entry: bash -c 'pwd'
        language: script
        pass_filenames: false
        verbose: true
