default_stages: [push]
repos:
-   repo: local
    hooks:
    -   id: run-smk-test
        name: run smoke test
        entry: ./scripts/run-tests.sh
        language: script
        pass_filenames: false
        verbose: true
